# Generated by Django 4.0.6 on 2022-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is the description of the product- Just a demo'),
            preserve_default=False,
        ),
    ]
